import express from 'express';
import accountRoutes from './accountRoutes.js';
import alertRoutes from './alertRoutes.js';
import authRoutes from './authRoutes.js';
import budgetRoutes from './budgetRoutes.js';
import categoryRoutes from './categoryRoutes.js';
import creditCardRoutes from './creditCardRoutes.js';
import demoRoutes from './demoRoutes.js';
import financialRoutes from './financialRoutes.js';
import financingRoutes from './financingRoutes.js';
import goalRoutes from './goalRoutes.js';
import healthRoutes from './healthRoutes.js';
import importRoutes from './importRoutes.js';
import installmentPlanRoutes from './installmentPlanRoutes.js';
import invoiceRoutes from './invoiceRoutes.js';
import recurringRuleRoutes from './recurringRuleRoutes.js';
import tituloRoutes from './tituloRoutes.js';
import transactionRoutes from './transactionRoutes.js';

const router = express.Router();

router.use('/accounts', accountRoutes);
router.use('/alerts', alertRoutes);
router.use('/auth', authRoutes);
router.use('/budgets', budgetRoutes);
router.use('/categories', categoryRoutes);
router.use('/credit-cards', creditCardRoutes);
router.use('/demo', demoRoutes);
router.use('/financial', financialRoutes);
router.use('/financings', financingRoutes);
router.use('/goals', goalRoutes);
router.use('/health', healthRoutes);
router.use('/import', importRoutes);
router.use('/installment-plans', installmentPlanRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/recurring-rules', recurringRuleRoutes);
router.use('/titulos', tituloRoutes);
router.use('/transactions', transactionRoutes);

export default router;
